MONIT - Fix: Visualizar cdas de laboratorio
andes/monitoreo-app pull request #47
Opened 2021-09-02 11:58 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MONIT-42

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-02 12:09 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4965](http://condorpiedra.andes.gob.ar:85/4965/mochawesome.html)
CYPRESS RUN: [3937](https://dashboard.cypress.io/projects/xr7gft/runs/3937/specs)
TEST START: 2021-09-02T12:09:44.101Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-02 13:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4966](http://condorpiedra.andes.gob.ar:85/4966/mochawesome.html)
CYPRESS RUN: [3938](https://dashboard.cypress.io/projects/xr7gft/runs/3938/specs)
TEST START: 2021-09-02T13:02:25.081Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-16 17:12 UTC, condorpiedra approved these changes

2021-11-03 11:12 UTC, kroce requested changes
Hice una prueba apuntando a prod y me muestra algunos registros repetidos. Adjunto captur
![duplicados](https://user-images.githubusercontent.com/18030170/140050468-05894179-b9f2-47d0-bace-d53535a90493.png)
a

2021-11-03 16:23 UTC, kroce approved these changes

2021-11-03 16:24 UTC, kroce commented
El bug que comenté no tenía que ver con este PR. Es algo que ya ocurre en la api

2021-11-03 16:42 UTC, merged