feat(MONIT):se agrega el selector multiple para el ámbito de la prest…
andes/monitoreo-app pull request #54
Opened 2022-03-29 13:27 UTC by leon-bravo

…ación

### Requerimiento
 

[MONIT-45](https://proyectos.andes.gob.ar/browse/MONIT-45)

### Funcionalidad desarrollada 

1. Se agrego un campo de selección múltiple para poder agregar el ámbito a la prestación
2. Se actualiza automáticamente el listado para traer los datos ya actualizados luego del cambio
3. Se re acomodaron los botones de editar y eliminar

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-04-20 13:44 UTC, martinebucarey requested changes

2022-04-20 13:44 UTC, martinebucarey commented on src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
> +    objectSelect2array(my_objectSelect) {
para parametros, variables, constantes, etc. usamos camelCase no solemos llamar a los parametros con _

2022-04-20 13:44 UTC, martinebucarey commented on src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
> +            if ( !Array.isArray(my_array ) ) {return result;}
Estos casos tratar de no hacerlos en una linea y con los espacios correctos para que quede mas limpio el código

2022-04-20 13:44 UTC, martinebucarey commented on src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
> +                nombre: 'AMBULATIORIO'
```suggestion
                nombre: 'AMBULATORIO'
```

2022-04-20 13:44 UTC, martinebucarey commented on src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
> +                nombre: 'INTERNACION'
```suggestion
                nombre: 'INTERNACIÓN'
```

2022-04-20 17:02 UTC, martinebucarey commented
Correr los test

2022-04-22 12:45 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6259](http://condorpiedra.andes.gob.ar:85/6259/mochawesome.html)
CYPRESS RUN: [5154](https://dashboard.cypress.io/projects/xr7gft/runs/5154/specs)
TEST START: 2022-04-22T12:45:44.671Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-04-25 12:14 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6272](http://condorpiedra.andes.gob.ar:85/6272/mochawesome.html)
CYPRESS RUN: [5167](https://dashboard.cypress.io/projects/xr7gft/runs/5167/specs)
TEST START: 2022-04-25T12:13:48.387Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-04-25 12:43 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6273](http://condorpiedra.andes.gob.ar:85/6273/mochawesome.html)
CYPRESS RUN: [5168](https://dashboard.cypress.io/projects/xr7gft/runs/5168/specs)
TEST START: 2022-04-25T12:43:12.662Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-26 13:06 UTC, leon-bravo commented on src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
> +                nombre: 'INTERNACION'
ahi ya hice todos los cambios, muchas gracias

2022-04-26 13:59 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6285](http://condorpiedra.andes.gob.ar:85/6285/mochawesome.html)
CYPRESS RUN: [5178](https://dashboard.cypress.io/projects/xr7gft/runs/5178/specs)
TEST START: 2022-04-26T13:59:00.652Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-27 17:42 UTC, AgosLizzi approved these changes

2022-04-27 17:43 UTC, merged