MONIT - Quitar el atributo requerido en mail y telefono
andes/monitoreo-app pull request #55
Opened 2022-07-01 12:30 UTC by leon-bravo

### Requerimiento
 
[MONIT-44](https://proyectos.andes.gob.ar/browse/MONIT-44) - Campos NO obligatorios - Monitoreo de activaciones
### Funcionalidad desarrollada 

1. Se quito el atributo requerido en el campo mail
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-01 17:42 UTC, martinebucarey requested changes

2022-07-01 17:42 UTC, martinebucarey commented on src/app/monitor-activaciones/monitoreo-activaciones.component.html
> +                                       [required]="false">
Por defecto vvienen en false, no hace falta aclararlo

2022-07-01 17:42 UTC, martinebucarey commented on src/app/monitor-activaciones/monitoreo-activaciones.component.ts
> +                        if (cuentas.length > 0) {
```suggestion
                        if (cuentas.length) {
```

2022-07-01 17:42 UTC, martinebucarey commented on src/app/monitor-activaciones/monitoreo-activaciones.component.ts
> +                        const cuentas = resultadoCuentas.filter(p => p.documento !== this.pacienteApp.documento);
si el filter se hace para saber si existen pacientes con ese documento y no hacer nada con el resultado, conviene usar la funcion some() de array: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-07-05 15:04 UTC, leon-bravo commented on src/app/monitor-activaciones/monitoreo-activaciones.component.ts
> +                        const cuentas = resultadoCuentas.filter(p => p.documento !== this.pacienteApp.documento);
Buenísimo!! Gracias por los comentarios, ahí ya realice los cambios, también cambiaron los requerimientos, ahora solo el teléfono puede ser blanco así que el código lo deje mas parecido a lo que era originalmente

2022-08-23 16:41 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [7501](http://condorpiedra.andes.gob.ar:85/7501/mochawesome.html)
CYPRESS RUN: [6306](https://dashboard.cypress.io/projects/xr7gft/runs/6306/specs)
TEST START: 2022-08-23T16:20:02.401Z
TOTAL: 398
SUCCESS: 391
FAIL: 6
SKIPPED: 1

2022-08-25 13:50 UTC, AgosLizzi requested changes
Si el campo email se utiliza para administrar las cuentas y por tanto es "obligatorio" tenerlo, yo le agregaría como recurso visual el asterisco.
![image](https://user-images.githubusercontent.com/72876985/186682563-7164ef68-6328-424d-b78f-346a680b2507.png)

2026-03-09 15:00 UTC, MarianoCampetella commented
> Si el campo email se utiliza para administrar las cuentas y por tanto es "obligatorio" tenerlo, yo le agregaría como recurso visual el asterisco. ![image](https://user-images.githubusercontent.com/72876985/186682563-7164ef68-6328-424d-b78f-346a680b2507.png)

Se corrigieron un par de detalles y también se agregó el asterisco de color rojo para señalar que es un campo obligatorio.

2026-03-09 15:01 UTC, Fabio-Ramirez approved these changes

2026-03-09 15:02 UTC, ma7payne approved these changes

2026-04-07 12:38 UTC, closed without merging