MONIT - Actualización de librerías y versión de Node
andes/monitoreo-app pull request #58
Opened 2022-11-25 14:42 UTC by ma7payne

### Requerimiento
https://proyectos.andes.gob.ar/browse/MONIT-49

### Funcionalidad desarrollada 
Se actualizaron las versiones de las librerias Plex y Plex Icons para alcanzar un upgrade de Node. 
La instalación y ejecución del proyecto no genera conflictos con la versión 14.21.1 de Node y las librerías actualizadas.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-09-19 18:37 UTC, maring0019 requested changes
Adjunto un archivo con los errores encontrados.
[ErrorMonit-49.odt](https://github.com/andes/monitoreo-app/files/12665375/ErrorMonit-49.odt)

2023-10-02 18:55 UTC, ma7payne commented
> Adjunto un archivo con los errores encontrados. [ErrorMonit-49.odt](https://github.com/andes/monitoreo-app/files/12665375/ErrorMonit-49.odt)

@maring0019 Gracias, en este caso los errores mostrados en el documento no son propios de los cambios realizados en la tarea. Pero conservo lo mencionado en el archivo para evaluar cada caso y reportar los errores en nuevas tareas.

2023-10-03 15:16 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9727](http://condorpiedra.andes.gob.ar:85/9727/mochawesome.html)
CYPRESS RUN: [8835](https://dashboard.cypress.io/projects/xr7gft/runs/8835/specs)
TEST START: 2023-10-03T15:16:16.126Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-10-04 16:07 UTC, maring0019 approved these changes

2023-10-05 15:59 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9743](http://condorpiedra.andes.gob.ar:85/9743/mochawesome.html)
CYPRESS RUN: [8854](https://dashboard.cypress.io/projects/xr7gft/runs/8854/specs)
TEST START: 2023-10-05T15:59:01.975Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-10-05 19:22 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9751](http://condorpiedra.andes.gob.ar:85/9751/mochawesome.html)
CYPRESS RUN: [8861](https://dashboard.cypress.io/projects/xr7gft/runs/8861/specs)
TEST START: 2023-10-05T19:22:05.230Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-11-28 15:33 UTC, silviroa approved these changes

2023-11-28 15:33 UTC, merged