MONIT - Actualización de ABM
andes/monitoreo-app pull request #61
Opened 2022-12-19 18:32 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MONIT-51

### Funcionalidad desarrollada 

1. Repara búsqueda de concepto. Al ingresar ConceptID se muestran los resultados de busqueda independientemente de que se haya ingresado algun valor en el campo Term.
2. Al crear un nuevo concepto turneable, si este ya existe en la BD, no permite volver a guardarlo y se muestra un mensaje de error.
3. Se remueve la implementación del método de eliminación de concepto turneable.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-09-05 14:50 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9557](http://condorpiedra.andes.gob.ar:85/9557/mochawesome.html)
CYPRESS RUN: [8680](https://dashboard.cypress.io/projects/xr7gft/runs/8680/specs)
TEST START: 2023-09-05T14:49:12.906Z
TOTAL: 388
SUCCESS: 381
FAIL: 6
SKIPPED: 1

2023-09-05 18:27 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9563](http://condorpiedra.andes.gob.ar:85/9563/mochawesome.html)
CYPRESS RUN: [8686](https://dashboard.cypress.io/projects/xr7gft/runs/8686/specs)
TEST START: 2023-09-05T18:26:40.345Z
TOTAL: 372
SUCCESS: 363
FAIL: 8
SKIPPED: 1

2023-09-14 16:22 UTC, maring0019 requested changes
Realizar los cambios solicitados en el código.

2023-10-02 18:48 UTC, ma7payne commented
> const termino = this.term;

Listo los cambios solicitados!

2023-10-04 16:54 UTC, maring0019 approved these changes

2024-03-06 18:23 UTC, silviroa approved these changes

2024-03-06 18:24 UTC, merged