MONIT - Actualizacion de ABM en novedades
andes/monitoreo-app pull request #62
Opened 2023-02-08 15:40 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MONIT-52
### Funcionalidad desarrollada 

1. Incorpora campo para agregar una palabra significativa para la novedad
2. Limita tamaño de imágenes a 5MB
3. Muestra mensaje de error al superar limite de 5MB

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

Link PR: https://github.com/andes/api/pull/1784
- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-02-14 12:39 UTC, MarianoCampetella commented
Maty encontre un comportamiento raro que en demo no me sucede! Cuando abro el sidebar y hago un scroll del listado, no solamente me muestra mas datos en dicho listado (revisar si este comportamiento esta bien) pero lo que si no es correcto es que me cierre el sidebar. Ya que estamos aprovecho a decirte que tenes algunos errores de linteo para solucionar. 

https://user-images.githubusercontent.com/65697028/218741003-2e913af3-75f8-40eb-89af-7879cc9b146c.mp4

2023-09-05 13:14 UTC, ma7payne commented
> Maty encontre un comportamiento raro que en demo no me sucede! Cuando abro el sidebar y hago un scroll del listado, no solamente me muestra mas datos en dicho listado (revisar si este comportamiento esta bien) pero lo que si no es correcto es que me cierre el sidebar. Ya que estamos aprovecho a decirte que tenes algunos errores de linteo para solucionar.
> 
>  Andes._.Monitoreo.-.14.February.2023.mp4

Hola, respecto a ese comportamiento parece que lo heredó en el momento en que hice el branch, nada en los cambios actuales  afecta el funcionamiento del sidebar. Deberiamos dejarlo como nueva tarea.

2023-09-05 14:19 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9556](http://condorpiedra.andes.gob.ar:85/9556/mochawesome.html)
CYPRESS RUN: [8679](https://dashboard.cypress.io/projects/xr7gft/runs/8679/specs)
TEST START: 2023-09-05T14:19:11.007Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-12 11:33 UTC, MarianoCampetella approved these changes

2023-09-12 11:34 UTC, MarianoCampetella commented
Se debe crear una nueva tarea para fixear el problema mencionado anteriormente!

2023-10-03 16:46 UTC, maring0019 requested changes
Sugiero cambiar el valor de comparación de los 5MB. Está escrito como 5000000 pero el valor exacto es 5242880. Ya que sino no aceptaría imágenes que si son menores a 5MB.

Me surgió una consulta. ¿Y lo del límite de 5MB por qué? ¿Por qué no otro valor?

2023-10-03 18:23 UTC, ma7payne commented
> Sugiero cambiar el valor de comparación de los 5MB. Está escrito como 5000000 pero el valor exacto es 5242880. Ya que sino no aceptaría imágenes que si son menores a 5MB.
> 
> Me surgió una consulta. ¿Y lo del límite de 5MB por qué? ¿Por qué no otro valor?

Listo el cambio!

2023-10-04 17:36 UTC, maring0019 approved these changes

2023-10-04 19:11 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9737](http://condorpiedra.andes.gob.ar:85/9737/mochawesome.html)
CYPRESS RUN: [8848](https://dashboard.cypress.io/projects/xr7gft/runs/8848/specs)
TEST START: 2023-10-04T19:11:29.547Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2024-02-29 18:21 UTC, merged