MONITOREO - Elementos Rups: Select estático
andes/monitoreo-app pull request #63
Opened 2023-05-04 18:38 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MONIT-54
### Funcionalidad desarrollada 

1. Al crear un átomo y seleccionar  Select Estático en Tipo Atomo, se agrega la posibilidad de agregar los ítems. Y también de eliminar el ítem.
2. Para el caso anterior. Al querer guardar el nuevo átomo. Solo se permite si al menos tiene cargado un item.
3. Para agregar un nuevo item, los campos Id y Label son obligatorios. No permite guardar espacios en blanco.
4. El botón Agregar Item despliega los campos Id y Label.
5. El botón + es para guardar el ítem.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-05-11 18:14 UTC, MarianoCampetella requested changes

2023-05-11 18:14 UTC, MarianoCampetella commented on src/app/rupers/components/atomo-create-update/atomo-create-update.component.ts
> +    params: any = {};
Me queda la duda porque se removió lo de " [key: string]: " ya que de las dos formas funcionan correctamente.

2023-05-11 18:14 UTC, MarianoCampetella commented on src/app/rupers/components/atomo-create-update/atomo-create-update.component.html
> +            <plex-title titulo="Items del Select Estático" size="sm">
Dejaría como título "Items" o "Items de ... (nombre orientativo) "
Por ejemplo items de Violencia.

2023-06-16 16:16 UTC, maring0019 commented
> No estaría demás agregar un tooltip con la leyenda "agregar" al botón verde + y otro al botón rojo con el signo del tacho de basura que diga "eliminar" También estaría bueno agregar un toast cada ves que se guardan los datos para brindarle la seguridad al usuario de que los mismos fueron guardados/editados con seguridad y no ocurrió ningún error.

Cambios hechos.

2023-06-16 16:33 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9097](http://condorpiedra.andes.gob.ar:85/9097/mochawesome.html)
CYPRESS RUN: [8247](https://dashboard.cypress.io/projects/xr7gft/runs/8247/specs)
TEST START: 2023-06-16T16:33:02.766Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-06-16 17:39 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9099](http://condorpiedra.andes.gob.ar:85/9099/mochawesome.html)
CYPRESS RUN: [8248](https://dashboard.cypress.io/projects/xr7gft/runs/8248/specs)
TEST START: 2023-06-16T17:39:33.531Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-03 18:16 UTC, MarianoCampetella commented
Mari quedaron de 10 las nuevas correcciones pero encontré los siguientes detalles a corregir:
- Los botones seria mejor que tengan la característica de sm en ves de md. 
- Primero consultaría si es necesario que el plex-text de "Label" tenga el atributo multiline=true de caso contrario se lo quitaría para que no se agrande y se vea diferente al plex-text de "id"
- El Tooltip del botón "Agregar" al estar con la característica por defecto en TOP se visualiza arriba lo cual se corta en la pantalla. En estos casos se puede utilizar la propiedad tooltipposition = left para decirle que lo muestre a la izquierda y de esta forma no se corte. 
- Cuando agrego un nuevo ítem y lo completo con los datos necesarios, si vuelvo a agregar otro nuevo ítem me permite guardar dejando los campos obligatorios en vacío!
![image](https://github.com/andes/monitoreo-app/assets/65697028/80a6d663-0f07-426d-887d-83db395081c9)

2023-07-05 15:05 UTC, maring0019 commented
> Mari quedaron de 10 las nuevas correcciones pero encontré los siguientes detalles a corregir:
> 
> * Los botones seria mejor que tengan la característica de sm en ves de md.
> * Primero consultaría si es necesario que el plex-text de "Label" tenga el atributo multiline=true de caso contrario se lo quitaría para que no se agrande y se vea diferente al plex-text de "id"
> * El Tooltip del botón "Agregar" al estar con la característica por defecto en TOP se visualiza arriba lo cual se corta en la pantalla. En estos casos se puede utilizar la propiedad tooltipposition = left para decirle que lo muestre a la izquierda y de esta forma no se corte.
> * Cuando agrego/edito un ítem de un átomo y lo completo con los datos necesarios, si vuelvo a agregar otro nuevo ítem me permite guardar el átomo dejando los campos obligatorios en vacío!
>   ![image](https://user-images.githubusercontent.com/65697028/250635707-80a6d663-0f07-426d-887d-83db395081c9.png)

Cambios realizados.

2023-07-05 15:06 UTC, maring0019 commented
> Mari quedaron de 10 las nuevas correcciones pero encontré los siguientes detalles a corregir:
> 
> * Los botones seria mejor que tengan la característica de sm en ves de md.
> * Primero consultaría si es necesario que el plex-text de "Label" tenga el atributo multiline=true de caso contrario se lo quitaría para que no se agrande y se vea diferente al plex-text de "id"
> * El Tooltip del botón "Agregar" al estar con la característica por defecto en TOP se visualiza arriba lo cual se corta en la pantalla. En estos casos se puede utilizar la propiedad tooltipposition = left para decirle que lo muestre a la izquierda y de esta forma no se corte.
> * Cuando agrego/edito un ítem de un átomo y lo completo con los datos necesarios, si vuelvo a agregar otro nuevo ítem me permite guardar el átomo dejando los campos obligatorios en vacío!
>   ![image](https://user-images.githubusercontent.com/65697028/250635707-80a6d663-0f07-426d-887d-83db395081c9.png)

Cambios realizados.

2024-03-06 18:45 UTC, silviroa approved these changes

2024-03-06 18:46 UTC, merged