MONITOREO - Agregar opción para dar de baja un elementoRUP
andes/monitoreo-app pull request #64
Opened 2023-08-07 16:21 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MONIT-56
### Funcionalidad desarrollada 

1.  Se agrega el botón eliminar para desactivar un elemento rup. 
2.  Se pone el campo activo=false.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-08-07 18:51 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9366](http://condorpiedra.andes.gob.ar:85/9366/mochawesome.html)
CYPRESS RUN: [8503](https://dashboard.cypress.io/projects/xr7gft/runs/8503/specs)
TEST START: 2023-08-07T18:51:01.781Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-07 19:04 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9367](http://condorpiedra.andes.gob.ar:85/9367/mochawesome.html)
CYPRESS RUN: [8504](https://dashboard.cypress.io/projects/xr7gft/runs/8504/specs)
TEST START: 2023-08-07T19:04:21.722Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-08 12:18 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9369](http://condorpiedra.andes.gob.ar:85/9369/mochawesome.html)
CYPRESS RUN: [8506](https://dashboard.cypress.io/projects/xr7gft/runs/8506/specs)
TEST START: 2023-08-08T12:16:45.431Z
TOTAL: 374
SUCCESS: 367
FAIL: 5
SKIPPED: 2

2023-08-08 14:49 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9373](http://condorpiedra.andes.gob.ar:85/9373/mochawesome.html)
CYPRESS RUN: [8510](https://dashboard.cypress.io/projects/xr7gft/runs/8510/specs)
TEST START: 2023-08-08T14:49:16.861Z
TOTAL: 399
SUCCESS: 393
FAIL: 4
SKIPPED: 2

2023-08-09 03:07 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9376](http://condorpiedra.andes.gob.ar:85/9376/mochawesome.html)
CYPRESS RUN: [8513](https://dashboard.cypress.io/projects/xr7gft/runs/8513/specs)
TEST START: 2023-08-09T03:05:57.659Z
TOTAL: 335
SUCCESS: 318
FAIL: 15
SKIPPED: 2

2023-08-11 15:03 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9393](http://condorpiedra.andes.gob.ar:85/9393/mochawesome.html)
CYPRESS RUN: [8530](https://dashboard.cypress.io/projects/xr7gft/runs/8530/specs)
TEST START: 2023-08-11T15:03:40.166Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-14 14:44 UTC, MarianoCampetella requested changes

2023-08-14 14:44 UTC, MarianoCampetella commented on src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.component.ts
> +    removeElemento(elementoRup: any) {
Ya que existe una interfaz de los elementos de RUP, remplazar el "any" por dicha interfaz.

2023-08-14 14:44 UTC, MarianoCampetella commented on src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.component.ts
> +                        this.plex.toast('success', 'El elemento se borro correctamente', 'Información', 2000);
Ya que estamos agregar acento a la palabra borró.

2023-08-14 14:46 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9407](http://condorpiedra.andes.gob.ar:85/9407/mochawesome.html)
CYPRESS RUN: [8544](https://dashboard.cypress.io/projects/xr7gft/runs/8544/specs)
TEST START: 2023-08-14T14:45:47.019Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-16 19:01 UTC, maring0019 commented on src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.component.ts
> +    removeElemento(elementoRup: any) {
> Ya que existe una interfaz de los elementos de RUP, remplazar el "any" por dicha interfaz.

Cambios hechos.

2023-08-16 19:01 UTC, maring0019 commented on src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.component.ts
> +                        this.plex.toast('success', 'El elemento se borro correctamente', 'Información', 2000);
> Ya que estamos agregar acento a la palabra borró.

Cambios hechos.

2023-08-17 17:50 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9467](http://condorpiedra.andes.gob.ar:85/9467/mochawesome.html)
CYPRESS RUN: [8594](https://dashboard.cypress.io/projects/xr7gft/runs/8594/specs)
TEST START: 2023-08-17T17:50:24.759Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-22 12:14 UTC, MarianoCampetella approved these changes

2024-03-07 11:22 UTC, silviroa commented
Para subir esta funcionalidad primero hay que agregar un control del lado de la app ANDES para que si un elementoRUP deja de estar activo, no permita crear nuevos registros, pero que si se pueda usar para visualizar los datos ya registrados usando el elemento.

2026-04-01 16:25 UTC, MarianoCampetella commented
> Para subir esta funcionalidad primero hay que agregar un control del lado de la app ANDES para que si un elementoRUP deja de estar activo, no permita crear nuevos registros, pero que si se pueda usar para visualizar los datos ya registrados usando el elemento.

Se creo la nueva tarea para resolver o charlar sobre lo propuesto: https://proyectos.andes.gob.ar/browse/RUP-524

2026-04-07 16:59 UTC, MCele commented
> > Para subir esta funcionalidad primero hay que agregar un control del lado de la app ANDES para que si un elementoRUP deja de estar activo, no permita crear nuevos registros, pero que si se pueda usar para visualizar los datos ya registrados usando el elemento.
> 
> Se creo la nueva tarea para resolver o charlar sobre lo propuesto: https://proyectos.andes.gob.ar/browse/RUP-524

Esto ya es posible mediante el atributo inactiveAt. Quizás agregando el dato inactiveAt ya alcanzaría. Se agrega esto en un nuevo commit, quedo a la espera de devoluciones.

2026-04-07 20:30 UTC, MCele approved these changes

2026-04-08 13:38 UTC, nicolasarana approved these changes

2026-04-10 14:24 UTC, MCele commented
Se agregan cambios pedidos y otros nuevos:

1. Mostrar en el listado los elementos rups inactivos,
2. mostrar fecha de inactivación del elemento Rup (inactivedAt),
3. identificar con badge en el titulo cuando un elemento Rup está inactivo y
4. no visualizar botón editar cuando el elemento Rup está inactivo.

NOTA: En la app de Andes con la variable inactivedAt se filtran los elementos Rups no diponibles, pero siguen siendo utilizados desde la visualización de la HUDS.

<img width="1888" height="731" alt="image" src="https://github.com/user-attachments/assets/e698367a-e62e-4acd-955e-bad26f658928" />

2026-05-18 17:40 UTC, merged